"""empty message

Revision ID: 7269dc7c24fc
Revises: 3f1974b833aa
Create Date: 2021-04-25 02:42:11.112654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7269dc7c24fc'
down_revision = '3f1974b833aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_product_unique', 'product_user', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_unique', 'product_user', type_='unique')
    # ### end Alembic commands ###
